apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: grafana-service
  labels:
    app: grafana-app
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    nodePort: 3000
    targetPort: 3000
    protocol: TCP
    name: grafana
  - port: 8086
    nodePort: 8086
    targetPort: 8086
    protocol: TCP
    name: grafana2db
  selector:
    app: grafana-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana-app
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      restartPolicy: Always
      containers:
      - image: grafana
        name: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana
        - containerPort: 8086
          name: grafana2db
