apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: phpmyadmin-service
  labels:
    app: phpmyadmin-app
spec:
  selector:
    app: phpmyadmin-app
  ports:
    - port: 5000
      nodePort: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin-app
    spec:
      restartPolicy: Always
      containers:
      - image: phpmyadmin
        name: phpmyadmin
        ports:
        - containerPort: 5000
          name: pma
        imagePullPolicy: Never
